import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Ovo,
  Libre_Baskerville,
  Lora,
  Rufina,
  Alegreya,
  Merriweather,
} from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import { ThemeInjector } from "@/components/theme-injector";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 配置 Ovo
const ovo = Ovo({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-ovo",
});

// 配置 Lora (通常用于正文，阅读感极佳)
const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora", // 定义变量名
  display: "swap",
});

// 配置 Rufina (通常用于标题，非常有设计感)
const rufina = Rufina({
  weight: ["400", "700"], // Rufina 必须指定字重
  subsets: ["latin"],
  variable: "--font-rufina", // 定义变量名
  display: "swap",
});

// 配置 Baskerville
const baskerville = Libre_Baskerville({
  weight: ["400", "700"], // 必须指定字重，Baskerville 通常用 400(常规) 和 700(粗体)
  subsets: ["latin"],
  variable: "--font-baskerville", // 定义 CSS 变量名
  display: "swap",
});

// 配置 Merriweather
const merriweather = Merriweather({
  weight: ["400", "700"], // merriweather 通常用 400(常规) 和 700(粗体)
  subsets: ["latin"],
  variable: "--font-merriweather", // 定义 CSS 变量名
  display: "swap",
});

// 配置 Alegreya
// 它是可变字体(Variable Font)，不需要指定 weight，除非你有特殊需求
const alegreya = Alegreya({
  subsets: ["latin"],
  variable: "--font-alegreya",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // NOTE: self-modified, 避免 SSR 和客户端主题不一致时警告 + 闪烁
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ovo.variable} ${baskerville.variable} ${lora.variable} ${rufina.variable} ${alegreya.variable} ${merriweather.variable} antialiased`}
      >
        {/* NOTE: self-modified, 避免闪白 / 闪暗 */}
        <ThemeInjector />
        <TRPCReactProvider>
          <NuqsAdapter>
            {children}
            <Toaster />
          </NuqsAdapter>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
